name: Docker

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  docker-build:
    runs-on: ubuntu-24.04
    env:
      DOCKER_REPO: ghcr.io/${{ github.repository }}
      RUBY_VERSION: 3.4.7
      NODE_VERSION: 22.20.0
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: ./build.sh
      - name: Login to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REPO }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'push'
      - name: Push Docker image
        run: ./push.sh
        if: github.event_name == 'push'
